#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════
#  12 Months — Alembic Migration Helper
#  Run from project root: ./make_migration.sh <command>
# ══════════════════════════════════════════════════════════════
set -e

BACKEND_DIR="$(cd "$(dirname "$0")/backend" && pwd)"
PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"

# Ensure .env exists
if [ ! -f "$PROJECT_ROOT/.env" ]; then
    echo "⚠️  .env not found! Copying from .env.example..."
    cp "$PROJECT_ROOT/.env.example" "$PROJECT_ROOT/.env"
    echo "✏️  Edit .env with real credentials before proceeding."
    exit 1
fi

# Copy .env to backend/ so alembic can find it (runs from backend/)
cp "$PROJECT_ROOT/.env" "$BACKEND_DIR/.env"

cd "$BACKEND_DIR"

case "$1" in
    init)
        # Create the first autogenerated migration from current models
        MSG="${2:-initial_schema}"
        echo "🌱 Creating migration: $MSG"
        alembic revision --autogenerate -m "$MSG"
        echo ""
        echo "✅ Migration file created in backend/migrations/versions/"
        echo "📝 Review it before applying!"
        echo ""
        echo "Next step: ./make_migration.sh upgrade"
        ;;

    upgrade)
        # Apply all pending migrations
        TARGET="${2:-head}"
        echo "⬆️  Upgrading database to: $TARGET"
        alembic upgrade "$TARGET"
        echo "✅ Database is up to date"
        ;;

    downgrade)
        # Roll back one or more migrations
        TARGET="${2:--1}"
        echo "⬇️  Downgrading database by: $TARGET"
        alembic downgrade "$TARGET"
        echo "✅ Rollback complete"
        ;;

    history)
        # Show migration history
        echo "📜 Migration history:"
        alembic history --verbose
        ;;

    current)
        # Show current migration revision
        echo "📍 Current revision:"
        alembic current
        ;;

    new)
        # Create empty migration (manual)
        MSG="${2:-manual_change}"
        echo "📝 Creating empty migration: $MSG"
        alembic revision -m "$MSG"
        echo "✅ Empty migration created — fill in upgrade()/downgrade()"
        ;;

    *)
        echo "╔══════════════════════════════════════════════════╗"
        echo "║        12 Months — Migration Helper              ║"
        echo "╚══════════════════════════════════════════════════╝"
        echo ""
        echo "Usage: ./make_migration.sh <command> [arg]"
        echo ""
        echo "Commands:"
        echo "  init [name]       Autogenerate migration from current models"
        echo "                    Default name: initial_schema"
        echo "  upgrade [target]  Apply migrations (default: head)"
        echo "  downgrade [n]     Roll back n steps (default: -1)"
        echo "  history           Show all migrations"
        echo "  current           Show current DB revision"
        echo "  new [name]        Create empty manual migration"
        echo ""
        echo "Examples:"
        echo "  ./make_migration.sh init"
        echo "  ./make_migration.sh upgrade"
        echo "  ./make_migration.sh downgrade -1"
        echo "  ./make_migration.sh init add_nps_column"
        ;;
esac
